apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: dh
spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
      - name: mysql
        image: mysql:8

        ports:
        - containerPort: 3306
        
        env:
        - name: MYSQL_DATABASE
          value: planner

        - name: MYSQL_USER
          value: planner_user

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: planner-db-secret
              key: MYSQL_PASSWORD

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: planner-db-secret
              key: MYSQL_ROOT_PASSWORD

        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "600m"
            memory: "1Gi"
