"""expand documents.text_extracted

Revision ID: 2f87bc9361b1
Revises: c6a4a8d49c90
Create Date: 2026-03-03 13:32:40.396237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f87bc9361b1'
down_revision = 'c6a4a8d49c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('text_extracted',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('text_extracted',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    # ### end Alembic commands ###
