"""init

Revision ID: c6a4a8d49c90
Revises: 
Create Date: 2026-03-03 05:38:02.734653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a4a8d49c90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syllabus_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('stored_filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('text_extracted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)

    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('daily_minutes', sa.Integer(), nullable=False),
    sa.Column('weekend_minutes', sa.Integer(), nullable=False),
    sa.Column('excluded_weekdays', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_exam_date'), ['exam_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_user_id'), ['user_id'], unique=False)

    op.create_table('syllabus_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['syllabus_topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'keyword', name='uq_topic_keyword')
    )
    with op.batch_alter_table('syllabus_keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_syllabus_keywords_keyword'), ['keyword'], unique=False)
        batch_op.create_index(batch_op.f('ix_syllabus_keywords_topic_id'), ['topic_id'], unique=False)

    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('scope_mode', sa.String(length=20), nullable=False),
    sa.Column('focus_keywords', sa.JSON(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('source_excerpt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quizzes_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_scope_mode'), ['scope_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_user_id'), ['user_id'], unique=False)

    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_plans_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_plans_plan_date'), ['plan_date'], unique=False)
        batch_op.create_index('ix_study_plans_user_date', ['user_id', 'plan_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_plans_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_plans_week_no'), ['week_no'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('is_review', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_is_review'), ['is_review'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_quiz_id'), ['quiz_id'], unique=False)

    op.create_table('attempt_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempt_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_answers_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_answers_question_id'), ['question_id'], unique=False)

    op.create_table('wrong_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('last_wrong_at', sa.DateTime(), nullable=False),
    sa.Column('mastered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_user_question_wrong')
    )
    with op.batch_alter_table('wrong_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wrong_answers_last_wrong_at'), ['last_wrong_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wrong_answers_mastered'), ['mastered'], unique=False)
        batch_op.create_index(batch_op.f('ix_wrong_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wrong_answers_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_wrong_answers_user_sort', ['user_id', 'mastered', 'wrong_count', 'last_wrong_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wrong_answers_wrong_count'), ['wrong_count'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wrong_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wrong_answers_wrong_count'))
        batch_op.drop_index('ix_wrong_answers_user_sort')
        batch_op.drop_index(batch_op.f('ix_wrong_answers_user_id'))
        batch_op.drop_index(batch_op.f('ix_wrong_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_wrong_answers_mastered'))
        batch_op.drop_index(batch_op.f('ix_wrong_answers_last_wrong_at'))

    op.drop_table('wrong_answers')
    with op.batch_alter_table('attempt_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_answers_attempt_id'))

    op.drop_table('attempt_answers')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_quiz_id'))

    op.drop_table('questions')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_quiz_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_is_review'))

    op.drop_table('attempts')
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_plans_week_no'))
        batch_op.drop_index(batch_op.f('ix_study_plans_user_id'))
        batch_op.drop_index('ix_study_plans_user_date')
        batch_op.drop_index(batch_op.f('ix_study_plans_plan_date'))
        batch_op.drop_index(batch_op.f('ix_study_plans_exam_id'))

    op.drop_table('study_plans')
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quizzes_user_id'))
        batch_op.drop_index(batch_op.f('ix_quizzes_source_type'))
        batch_op.drop_index(batch_op.f('ix_quizzes_scope_mode'))
        batch_op.drop_index(batch_op.f('ix_quizzes_document_id'))

    op.drop_table('quizzes')
    with op.batch_alter_table('syllabus_keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_syllabus_keywords_topic_id'))
        batch_op.drop_index(batch_op.f('ix_syllabus_keywords_keyword'))

    op.drop_table('syllabus_keywords')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_user_id'))
        batch_op.drop_index(batch_op.f('ix_exams_exam_date'))

    op.drop_table('exams')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))

    op.drop_table('documents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('topics')
    op.drop_table('syllabus_topics')
    # ### end Alembic commands ###
