apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: linuxmaster
  labels:
    app: linuxmaster
    tier: db
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
